[package]
name = "random-service"
version = "0.1.0"
authors = ["tennix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14"
rand  = "0.8"
pretty_env_logger = "0.4"
log   = "0.4"
dotenv = "0.15"

